name: morning
on:
  schedule:
  - cron:  '1 0,10 * * *'
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest
    name: goodmorning

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: master

    - name: sender
      uses: actions/setup-python@v2
      with:
        python-version: '3.7.5'
        architecture: 'x64'
    - run: pip install -r ./requirements.txt && python ./main.py

    env:
      APP_ID: ${{ secrets.APP_ID }}
      APP_SECRET: ${{ secrets.APP_SECRET }}
      TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
      USER_ID: ${{ secrets.USER_ID }}
      START_DATE: ${{ secrets.START_DATE }}
      BIRTHDAY: ${{ secrets.BIRTHDAY }}
      CITY: ${{ secrets.CITY }}
      USER_ID2: ${{ secrets.USER_ID2 }}
      HF_CITY_HTML: ${{ secrets.HF_CITY_HTML }}
      HF_CARD_WRAP: ${{ secrets.HF_CARD_WRAP }}
      HF_CARD_ABSTRACT: ${{ secrets.HF_CARD_ABSTRACT }}